workflows:
  build-android:
    name: Build Android APK (Capacitor + Vite)
    environment:
      vars:
        PACKAGE_NAME: "com.zoolka.app"
      node: 20.12.2
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Copy web assets to native
        script: |
          npx cap copy android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
