// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqyreqrpuyvfvrhovjcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxeXJlcXJwdXl2ZnZyaG92amNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTgwODQsImV4cCI6MjA1OTY3NDA4NH0.66GCy3NHvRv9a0Oh4lPam7ljD0FNLbTdItrNs3GdNeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);